### ISSUE TITLE
Non-deterministic action outcomes (failure in movement). Movement actions might fail, causing the agent to return to the source node.

### ISSUE THREAD

**Issue by m312z** [strathclyde-artificial-intelligence/craft-bots#1]
In the case of movement failure, what happens with the agent? They should presumable remain where they are (in the middle between two nodes) or return to the source node.

Second, whe is chance of failure checked? Continuously throughout the movement? That would make sense to me, and mean longer traversals are more likely to fail, but can be unintuitive to configure. 5% of failure continuously across a link is actually a much higher overall chance of failure, depending upon the length of the link. Is there a nice way to do this?

**Comment by Roedhip** [comment]
Uncertainties in success of a movement action seem like they could just be replaced with uncertainty in duration of the movement action. A failed movement can just be attempted again, so failure just leads to a longer time. There could be a slight difference if failure to move is an opportunity to take a different action, but that is quite niche.

**Comment by m312z** [comment]
Following on that logic - that failure of a movement action indicates that the connection is actually blocked. Perhaps non-determinism in movement should be split into a separate module. Failures in the other actions already add an unexpected time delay, and non-deterministic durations are covered elsewhere.

Probabilities of link failure is one possibility for a separate module - but its probably a good idea to look first into what are the common challenges with physical agents. I'll pose this question to Oscar and Gerard as roboticists. I imagine they will mention teh robot getting stuck and being unable to move, or losing localisation and ending up in the wrong place...

**Comment by Roedhip** [comment]
Some ideas that could be implemented:
 - Loss of a connection between nodes, should be repairable or temporary (this represents a risk that every time an agent attempts to cross a connection, the connection might become damaged)
 - Discovering that the connection is blocked (for this case, a connection becoming blocked should not depend on whether or not an agent is trying to cross the connection)
 - Agent breaking down, requiring assistance from another agent (rather than adding an extra location for every connection, the robot should probably be at either the start or end of its movement when it breaks down)

**Comment by m312z** [comment]
> Loss of a connection between nodes, should be repairable or temporary (this represents a risk that every time an agent attempts to cross a connection, the connection might become damaged)

This could be good. Similar to the red resource, the connections might be only usable within time intervals. However, in contrast to the resource, the time intervals would be unknown.

> Discovering that the connection is blocked (for this case, a connection becoming blocked should not depend on whether or not an agent is trying to cross the connection)

I also like this - discovering that the connection is blocked and removing it from the map. In both this case and the one described above, it is not a random chance of action failure that is rolled when the movement takes place, but there is an underlying ground truth initially not known.

> Agent breaking down, requiring assistance from another agent (rather than adding an extra location for every connection, the robot should probably be at either the start or end of its movement when it breaks down)

This will require more actions for rescuing the stranded agent. Better to keep the scenario simply for now and not add too much complexity in support of uncertainty.

**Comment by m312z** [comment]
Resolved and implemented.
